project:
  type: website

website:
  output-dir: _site
  render:
    - "*.qmd"
  publish:
    gh-pages: true
  sidebar:
    logo: images/dxdt_twins_logo_only.png
    style: "docked"
  navbar:
    background: primary
    search: false
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: about.qmd
            text: People
          - href: work.qmd
            text: Our Work
      - text: Services
        menu:
          - text: Training and Workshops
            href: training.qmd
          - text: Data Management and Systems Design
            href: datamanagement.qmd
          - text: Data Dashboards
            href: dashboards.qmd
          - text: Environmental Modeling
            href: modeling.qmd
      - href: contact.qmd
        text: Contact
  page-footer:
    border: true
    left: "&#169; 2025 Geraldine Klarenberg"
    center: "<img src='images/plants.jpg' style='height:40px; width:800px; object-fit:cover;'>"
    right: "made with {{< fa heart title='love' aria-hidden='true' >}} & [Quarto](https://quarto.org)"
    
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

editor: source

