project:
  type: website

website:
  sidebar:
    logo: images/dxdt_twins_logo_only.png
    style: "docked"
  navbar:
    background: primary
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Our Work
      - text: Services
        menu:
          - text: Data Dashboards
            href: dashboards.qmd
          - text: Environmental Modeling
            href: modeling.qmd
      - href: contact.qmd
        text: Contact Us

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

editor: visual

