project:
  type: website

website:
  title: "dxdt Scientific"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: work.qmd
        text: Our Work
      - href: contact.qmd
        text: Contact Us

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

